"""Per-chat queue for voice messages generated by LLM tool calls.

辉夜通过 send_voice_note 工具调出的语音片段不能立刻在 tool 执行的上下文里
发送给 Telegram(tool 执行只产出文本 tool_result,副作用要延到外面做)。
所以 tool 执行时把合成好的音频字节塞进这个 per-chat 队列,handler 在文字
回复的 segments 全部发送完毕后调用 drain() 取出,依次 send_voice。

队列是 module-level 的 (gateway 单进程异步运行,threading.Lock 够用),
按 chat_id 隔离,避免两个 chat 的语音互相污染。
"""
from __future__ import annotations

import threading
from dataclasses import dataclass


@dataclass
class VoiceNote:
    audio: bytes
    text: str                     # 送给 TTS 念的原文 (即 what was synthesized)
    caption: str = ""             # 语音气泡下方显示的文字 (通常 = text,或双语扩展版)
    mime_type: str = "audio/mpeg"
    duration_ms: int = 0


_lock = threading.Lock()
_queue: dict[str, list[VoiceNote]] = {}


def enqueue(chat_id: str, note: VoiceNote) -> None:
    """Push a voice note onto the given chat's queue."""
    key = str(chat_id)
    with _lock:
        _queue.setdefault(key, []).append(note)


def drain(chat_id: str) -> list[VoiceNote]:
    """Pop all pending voice notes for the chat. Safe to call when empty."""
    key = str(chat_id)
    with _lock:
        return _queue.pop(key, [])


def queue_size(chat_id: str) -> int:
    key = str(chat_id)
    with _lock:
        return len(_queue.get(key, []))
